spring:
  cloud:
    function:
      definition: pageEventConsumer;pageEventSupplier;pageEventFunction;kStreamFunction
    stream:
      bindings:
        pageEventConsumer-in-0:
          destination: R1
        pageEventSupplier-out-0:
          destination: R2
        pageEventFunction-in-0:
          destination: R2
        pageEventFunction-out-0:
          destination: R3
        kStreamFunction-in-0:
          destination: R2
        kStreamFunction-out-0:
          destination: R4

